name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [
            macos-13, # x64
            macos-14, # ARM
            ubuntu-latest,
            # windows-latest,
          ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: |
          unzip npm-packages.zip
          tar -xvzf rescript-11.1.3-rc.1-da88460.tgz
          npm install package/

      - name: Build
        continue-on-error: true
        run: ./node_modules/.bin/rescript build

      - name: Build with warn-error
        continue-on-error: true
        run: ./node_modules/.bin/rescript build -warn-error +32

      - name: Build without warn-error
        continue-on-error: true
        run: ./node_modules/.bin/rescript build
